Add --legacy flag, for compatibility with Xcode 16
slidoapp/xcresulttool pull request #3
Opened 2024-09-20 19:47 UTC by gemmakbarlow

Some related discussion can be seen here - https://github.com/fastlane/fastlane/issues/22132

2024-09-20 19:50 UTC, gemmakbarlow commented
@jozefizso - this is my first attempt at Typescript - I welcome any testing pointers.

2024-10-03 14:22 UTC, JJdeGroot commented
Does anyone what the non-deprecated alternative is for this command?

**xcrun xcresulttool -h**       
```                                                                                    
OVERVIEW: Xcode Result Bundle Tool (version 23028).

USAGE: xcresulttool <subcommand>

OPTIONS:
  --version               Show the version.
  -h, --help              Show help information.

SUBCOMMANDS:
  get                     Get Result Bundle contents.
  export                  Export Result Bundle contents.
  graph                   Print Result Bundle Object Graph. This subcommand is deprecated and will be removed in a future release, consider using
                          `xcresulttool get test-report` instead.
  metadata                Result Bundle Metadata.
  formatDescription       Result Bundle Format Description. This subcommand is deprecated and will be removed in a future release.
  merge                   Merge Result Bundles.
```

`graph` and `formatDescription` have been deprecated. For `graph`, it says: consider using `xcresulttool get test-report` instead.

**xcrun xcresulttool get -h**
```
OVERVIEW: Get Result Bundle contents.

USAGE: xcresulttool get <subcommand>

OPTIONS:
  --version               Show the version.
  -h, --help              Show help information.

SUBCOMMANDS:
  object (default)        Get Result Bundle Object. This subcommand is deprecated and will be removed in a future release, consider using
                          `xcresulttool get test-report` instead.
  test-results            Get a high level description of what was tested, the destinations on which tests ran, and other metadata along with all
                          failures reported.
  build-results           Get a high level description of build action, the run destination for which the build was performed, and other metadata
                          along with warnings and issues.
  log                     Get build, action, or console log from Result Bundle.

  See 'xcresulttool help get <subcommand>' for detailed help.
```

For `get` it's odd that a deprecated subcommand `object` is the default.

It also tells you to "consider `xcresulttool get test-report` instead."

However, `test-report` is not listed as subcommand.... but it does exist.

**xcrun xcresulttool get test-report -h**
```
OVERVIEW: Get Result Bundle Object. This subcommand is deprecated and will be removed in a future release, consider using `xcresulttool get
test-report` instead.

USAGE: xcresulttool get object [--legacy] --path <path> [--id <id>] [--version <version>] [--format <format>]

OPTIONS:
  --legacy                Required to enable legacy API.
  --path <path>           The result bundle path.
  --id <id>               The ID of the object [optional, assumes rootID if not specified].
  --version <version>     For incomplete result bundles (lacking Info.plist), specify version explicitly [optional, assumes latest version if not
                          specified].
  --format <format>       The output format. (values: json, raw; default: raw)
  --version               Show the version.
  -h, --help              Show help information.
```

This command is deprecated as well.... it appears to be an alias for get object, which is also mentioned in the usage?

All in all it's super confusing and unclear what the undeprecated way is.

2024-10-03 14:34 UTC, JJdeGroot commented
Relevant topic: https://forums.developer.apple.com/forums/thread/763050

Looks like `xcrun xcresulttool get test-results summary --path X.xcresult` is a close alternative, at least for our use case it contains the information we need.

2024-10-21 16:31 UTC, jozefizso commented
Hello, we are sorry we missed this pull request. I will take a look at it as we are at the transition to Xcode 16.

2024-10-22 13:42 UTC, jozefizso requested changes

2024-10-22 13:42 UTC, jozefizso commented on src/xcode.ts
> +    throw new Error('Unable to determine Xcode version');
I would prefer the script to continue working if it cannot determine the Xcode version instead of bailing out.

2024-10-22 13:42 UTC, jozefizso commented on src/main.ts
> +  if (xcodeVersion >= 16) {
I would add the `--legacy` only if the Xcode is exactly 16. Later releases may not have this flag:


```
Error: This command is deprecated and will be removed in a future release, --legacy flag is required to use it.
```

2024-10-22 13:42 UTC, jozefizso commented on src/main.ts
> +
Please, use the same code style as is in the whole project.

2024-10-22 13:43 UTC, jozefizso commented
Hi @gemmakbarlow, I have some feedback for the PR:

1. It is always better to create PR from a topic/feature branch and not the master branch. This would allow us to make small adjustments to the code before merging if it was on a topic branch.
2. I would prefer script to continue working if it cannot determine the Xcode version instead of bailing out
3. The code formatting and styling should match other source code.

2024-10-22 13:46 UTC, gemmakbarlow commented
> Hi @gemmakbarlow, I have some feedback for the PR:
> 
> 1. It is always better to create PR from a topic/feature branch and not the master branch. This would allow us to make small adjustments to the code before merging if it was on a topic branch.
> 2. I would prefer script to continue working if it cannot determine the Xcode version instead of bailing out
> 3. The code formatting and styling should match other source code.

All very valid, thank-you for the feedback. I hope to get some time to address those comments later in the week. 

If you need to proceed with another approach in the interim, please go ahead, as I'm a little swamped at the moment.

2024-10-29 16:01 UTC, jozefizso commented
I am closing this PR as the fix was implemented in #10

2024-10-29 16:01 UTC, closed without merging

2024-10-29 16:02 UTC, jozefizso commented
Release is ready: https://github.com/slidoapp/xcresulttool/releases/tag/v3.1.0